#ifndef VULKAN_WRAPPER_H
#define VULKAN_WRAPPER_H

#include <dlfcn.h>

#include "vortek.h"

typedef struct VulkanWrapper {
    PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;
    PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;
#if ENABLE_VALIDATION_LAYER
    PFN_vkCreateDebugReportCallbackEXT vkCreateDebugReportCallback;
    PFN_vkDestroyDebugReportCallbackEXT vkDestroyDebugReportCallback;
#endif
    PFN_vkCreateInstance vkCreateInstance;
    PFN_vkDestroyInstance vkDestroyInstance;
    PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;
    PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;
    PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
    PFN_vkGetPhysicalDeviceFeatures vkGetPhysicalDeviceFeatures;
    PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties;
    PFN_vkGetPhysicalDeviceImageFormatProperties vkGetPhysicalDeviceImageFormatProperties;
    PFN_vkCreateDevice vkCreateDevice;
    PFN_vkDestroyDevice vkDestroyDevice;
    PFN_vkEnumerateInstanceVersion vkEnumerateInstanceVersion;
    PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties;
    PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties;
    PFN_vkGetDeviceQueue vkGetDeviceQueue;
    PFN_vkQueueSubmit vkQueueSubmit;
    PFN_vkQueueWaitIdle vkQueueWaitIdle;
    PFN_vkDeviceWaitIdle vkDeviceWaitIdle;
    PFN_vkAllocateMemory vkAllocateMemory;
    PFN_vkFreeMemory vkFreeMemory;
    PFN_vkMapMemory vkMapMemory;
    PFN_vkUnmapMemory vkUnmapMemory;
    PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;
    PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;
    PFN_vkGetDeviceMemoryCommitment vkGetDeviceMemoryCommitment;
    PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
    PFN_vkBindBufferMemory vkBindBufferMemory;
    PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
    PFN_vkBindImageMemory vkBindImageMemory;
    PFN_vkGetImageSparseMemoryRequirements vkGetImageSparseMemoryRequirements;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties vkGetPhysicalDeviceSparseImageFormatProperties;
    PFN_vkQueueBindSparse vkQueueBindSparse;
    PFN_vkCreateFence vkCreateFence;
    PFN_vkDestroyFence vkDestroyFence;
    PFN_vkResetFences vkResetFences;
    PFN_vkGetFenceStatus vkGetFenceStatus;
    PFN_vkWaitForFences vkWaitForFences;
    PFN_vkCreateSemaphore vkCreateSemaphore;
    PFN_vkDestroySemaphore vkDestroySemaphore;
    PFN_vkCreateEvent vkCreateEvent;
    PFN_vkDestroyEvent vkDestroyEvent;
    PFN_vkGetEventStatus vkGetEventStatus;
    PFN_vkSetEvent vkSetEvent;
    PFN_vkResetEvent vkResetEvent;
    PFN_vkCreateQueryPool vkCreateQueryPool;
    PFN_vkDestroyQueryPool vkDestroyQueryPool;
    PFN_vkGetQueryPoolResults vkGetQueryPoolResults;
    PFN_vkResetQueryPoolEXT vkResetQueryPool;
    PFN_vkCreateBuffer vkCreateBuffer;
    PFN_vkDestroyBuffer vkDestroyBuffer;
    PFN_vkCreateBufferView vkCreateBufferView;
    PFN_vkDestroyBufferView vkDestroyBufferView;
    PFN_vkCreateImage vkCreateImage;
    PFN_vkDestroyImage vkDestroyImage;
    PFN_vkGetImageSubresourceLayout vkGetImageSubresourceLayout;
    PFN_vkCreateImageView vkCreateImageView;
    PFN_vkDestroyImageView vkDestroyImageView;
    PFN_vkCreateShaderModule vkCreateShaderModule;
    PFN_vkDestroyShaderModule vkDestroyShaderModule;
    PFN_vkCreatePipelineCache vkCreatePipelineCache;
    PFN_vkDestroyPipelineCache vkDestroyPipelineCache;
    PFN_vkGetPipelineCacheData vkGetPipelineCacheData;
    PFN_vkMergePipelineCaches vkMergePipelineCaches;
    PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines;
    PFN_vkCreateComputePipelines vkCreateComputePipelines;
    PFN_vkDestroyPipeline vkDestroyPipeline;
    PFN_vkCreatePipelineLayout vkCreatePipelineLayout;
    PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;
    PFN_vkCreateSampler vkCreateSampler;
    PFN_vkDestroySampler vkDestroySampler;
    PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;
    PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;
    PFN_vkCreateDescriptorPool vkCreateDescriptorPool;
    PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;
    PFN_vkResetDescriptorPool vkResetDescriptorPool;
    PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;
    PFN_vkFreeDescriptorSets vkFreeDescriptorSets;
    PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;
    PFN_vkCreateFramebuffer vkCreateFramebuffer;
    PFN_vkDestroyFramebuffer vkDestroyFramebuffer;
    PFN_vkCreateRenderPass vkCreateRenderPass;
    PFN_vkDestroyRenderPass vkDestroyRenderPass;
    PFN_vkGetRenderAreaGranularity vkGetRenderAreaGranularity;
    PFN_vkCreateCommandPool vkCreateCommandPool;
    PFN_vkDestroyCommandPool vkDestroyCommandPool;
    PFN_vkResetCommandPool vkResetCommandPool;
    PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;
    PFN_vkFreeCommandBuffers vkFreeCommandBuffers;
    PFN_vkBeginCommandBuffer vkBeginCommandBuffer;
    PFN_vkEndCommandBuffer vkEndCommandBuffer;
    PFN_vkResetCommandBuffer vkResetCommandBuffer;
    PFN_vkCmdBindPipeline vkCmdBindPipeline;
    PFN_vkCmdSetViewport vkCmdSetViewport;
    PFN_vkCmdSetScissor vkCmdSetScissor;
    PFN_vkCmdSetLineWidth vkCmdSetLineWidth;
    PFN_vkCmdSetDepthBias vkCmdSetDepthBias;
    PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants;
    PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds;
    PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask;
    PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask;
    PFN_vkCmdSetStencilReference vkCmdSetStencilReference;
    PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;
    PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer;
    PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers;
    PFN_vkCmdDraw vkCmdDraw;
    PFN_vkCmdDrawIndexed vkCmdDrawIndexed;
    PFN_vkCmdDrawIndirect vkCmdDrawIndirect;
    PFN_vkCmdDrawIndexedIndirect vkCmdDrawIndexedIndirect;
    PFN_vkCmdDispatch vkCmdDispatch;
    PFN_vkCmdDispatchIndirect vkCmdDispatchIndirect;
    PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
    PFN_vkCmdCopyImage vkCmdCopyImage;
    PFN_vkCmdBlitImage vkCmdBlitImage;
    PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage;
    PFN_vkCmdCopyImageToBuffer vkCmdCopyImageToBuffer;
    PFN_vkCmdUpdateBuffer vkCmdUpdateBuffer;
    PFN_vkCmdFillBuffer vkCmdFillBuffer;
    PFN_vkCmdClearColorImage vkCmdClearColorImage;
    PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage;
    PFN_vkCmdClearAttachments vkCmdClearAttachments;
    PFN_vkCmdResolveImage vkCmdResolveImage;
    PFN_vkCmdSetEvent vkCmdSetEvent;
    PFN_vkCmdResetEvent vkCmdResetEvent;
    PFN_vkCmdWaitEvents vkCmdWaitEvents;
    PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier;
    PFN_vkCmdBeginQuery vkCmdBeginQuery;
    PFN_vkCmdEndQuery vkCmdEndQuery;
    PFN_vkCmdBeginConditionalRenderingEXT vkCmdBeginConditionalRendering;
    PFN_vkCmdEndConditionalRenderingEXT vkCmdEndConditionalRendering;
    PFN_vkCmdResetQueryPool vkCmdResetQueryPool;
    PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp;
    PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults;
    PFN_vkCmdPushConstants vkCmdPushConstants;
    PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass;
    PFN_vkCmdNextSubpass vkCmdNextSubpass;
    PFN_vkCmdEndRenderPass vkCmdEndRenderPass;
    PFN_vkCmdExecuteCommands vkCmdExecuteCommands;
    PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilities;
    PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormats;
    PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModes;
    PFN_vkCreateSwapchainKHR vkCreateSwapchain;
    PFN_vkDestroySwapchainKHR vkDestroySwapchain;
    PFN_vkGetSwapchainImagesKHR vkGetSwapchainImages;
    PFN_vkAcquireNextImageKHR vkAcquireNextImage;
    PFN_vkQueuePresentKHR vkQueuePresent;
    PFN_vkGetPhysicalDeviceFeatures2KHR vkGetPhysicalDeviceFeatures2;
    PFN_vkGetPhysicalDeviceProperties2KHR vkGetPhysicalDeviceProperties2;
    PFN_vkGetPhysicalDeviceFormatProperties2KHR vkGetPhysicalDeviceFormatProperties2;
    PFN_vkGetPhysicalDeviceImageFormatProperties2KHR vkGetPhysicalDeviceImageFormatProperties2;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR vkGetPhysicalDeviceQueueFamilyProperties2;
    PFN_vkGetPhysicalDeviceMemoryProperties2KHR vkGetPhysicalDeviceMemoryProperties2;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR vkGetPhysicalDeviceSparseImageFormatProperties2;
    PFN_vkCmdPushDescriptorSetKHR vkCmdPushDescriptorSet;
    PFN_vkTrimCommandPoolKHR vkTrimCommandPool;
    PFN_vkGetPhysicalDeviceExternalBufferProperties vkGetPhysicalDeviceExternalBufferProperties;
    PFN_vkGetMemoryFdKHR vkGetMemoryFd;
    PFN_vkGetPhysicalDeviceExternalSemaphoreProperties vkGetPhysicalDeviceExternalSemaphoreProperties;
    PFN_vkGetSemaphoreFdKHR vkGetSemaphoreFd;
    PFN_vkGetPhysicalDeviceExternalFenceProperties vkGetPhysicalDeviceExternalFenceProperties;
    PFN_vkGetFenceFdKHR vkGetFenceFd;
    PFN_vkEnumeratePhysicalDeviceGroups vkEnumeratePhysicalDeviceGroups;
    PFN_vkGetDeviceGroupPeerMemoryFeatures vkGetDeviceGroupPeerMemoryFeatures;
    PFN_vkBindBufferMemory2 vkBindBufferMemory2;
    PFN_vkBindImageMemory2 vkBindImageMemory2;
    PFN_vkCmdSetDeviceMask vkCmdSetDeviceMask;
    PFN_vkAcquireNextImage2KHR vkAcquireNextImage2;
    PFN_vkCmdDispatchBase vkCmdDispatchBase;
    PFN_vkGetPhysicalDevicePresentRectanglesKHR vkGetPhysicalDevicePresentRectangles;
    PFN_vkCreateDescriptorUpdateTemplateKHR vkCreateDescriptorUpdateTemplate;
    PFN_vkDestroyDescriptorUpdateTemplateKHR vkDestroyDescriptorUpdateTemplate;
    PFN_vkUpdateDescriptorSetWithTemplateKHR vkUpdateDescriptorSetWithTemplate;
    PFN_vkCmdSetSampleLocationsEXT vkCmdSetSampleLocations;
    PFN_vkGetPhysicalDeviceMultisamplePropertiesEXT vkGetPhysicalDeviceMultisampleProperties;
    PFN_vkGetBufferMemoryRequirements2KHR vkGetBufferMemoryRequirements2;
    PFN_vkGetImageMemoryRequirements2KHR vkGetImageMemoryRequirements2;
    PFN_vkGetImageSparseMemoryRequirements2KHR vkGetImageSparseMemoryRequirements2;
    PFN_vkGetDeviceBufferMemoryRequirements vkGetDeviceBufferMemoryRequirements;
    PFN_vkGetDeviceImageMemoryRequirements vkGetDeviceImageMemoryRequirements;
    PFN_vkGetDeviceImageSparseMemoryRequirements vkGetDeviceImageSparseMemoryRequirements;
    PFN_vkCreateSamplerYcbcrConversionKHR vkCreateSamplerYcbcrConversion;
    PFN_vkDestroySamplerYcbcrConversionKHR vkDestroySamplerYcbcrConversion;
    PFN_vkGetDeviceQueue2 vkGetDeviceQueue2;
    PFN_vkGetDescriptorSetLayoutSupportKHR vkGetDescriptorSetLayoutSupport;
    PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsEXT vkGetPhysicalDeviceCalibrateableTimeDomains;
    PFN_vkGetCalibratedTimestampsEXT vkGetCalibratedTimestamps;
    PFN_vkCreateRenderPass2KHR vkCreateRenderPass2;
    PFN_vkCmdBeginRenderPass2KHR vkCmdBeginRenderPass2;
    PFN_vkCmdNextSubpass2KHR vkCmdNextSubpass2;
    PFN_vkCmdEndRenderPass2KHR vkCmdEndRenderPass2;
    PFN_vkGetSemaphoreCounterValueKHR vkGetSemaphoreCounterValue;
    PFN_vkWaitSemaphoresKHR vkWaitSemaphores;
    PFN_vkSignalSemaphoreKHR vkSignalSemaphore;
    PFN_vkGetAndroidHardwareBufferPropertiesANDROID vkGetAndroidHardwareBufferPropertiesANDROID;
    PFN_vkCmdDrawIndirectCountKHR vkCmdDrawIndirectCount;
    PFN_vkCmdDrawIndexedIndirectCountKHR vkCmdDrawIndexedIndirectCount;
    PFN_vkCmdBindTransformFeedbackBuffersEXT vkCmdBindTransformFeedbackBuffers;
    PFN_vkCmdBeginTransformFeedbackEXT vkCmdBeginTransformFeedback;
    PFN_vkCmdEndTransformFeedbackEXT vkCmdEndTransformFeedback;
    PFN_vkCmdBeginQueryIndexedEXT vkCmdBeginQueryIndexed;
    PFN_vkCmdEndQueryIndexedEXT vkCmdEndQueryIndexed;
    PFN_vkCmdDrawIndirectByteCountEXT vkCmdDrawIndirectByteCount;
    PFN_vkGetBufferOpaqueCaptureAddress vkGetBufferOpaqueCaptureAddress;
    PFN_vkGetBufferDeviceAddress vkGetBufferDeviceAddress;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddress vkGetDeviceMemoryOpaqueCaptureAddress;
    PFN_vkCmdSetLineStippleEXT vkCmdSetLineStipple;
    PFN_vkCmdSetCullModeEXT vkCmdSetCullMode;
    PFN_vkCmdSetFrontFaceEXT vkCmdSetFrontFace;
    PFN_vkCmdSetPrimitiveTopologyEXT vkCmdSetPrimitiveTopology;
    PFN_vkCmdSetViewportWithCountEXT vkCmdSetViewportWithCount;
    PFN_vkCmdSetScissorWithCountEXT vkCmdSetScissorWithCount;
    PFN_vkCmdBindVertexBuffers2EXT vkCmdBindVertexBuffers2;
    PFN_vkCmdSetDepthTestEnableEXT vkCmdSetDepthTestEnable;
    PFN_vkCmdSetDepthWriteEnableEXT vkCmdSetDepthWriteEnable;
    PFN_vkCmdSetDepthCompareOpEXT vkCmdSetDepthCompareOp;
    PFN_vkCmdSetDepthBoundsTestEnableEXT vkCmdSetDepthBoundsTestEnable;
    PFN_vkCmdSetStencilTestEnableEXT vkCmdSetStencilTestEnable;
    PFN_vkCmdSetStencilOpEXT vkCmdSetStencilOp;
    PFN_vkCmdSetRasterizerDiscardEnable vkCmdSetRasterizerDiscardEnable;
    PFN_vkCmdSetDepthBiasEnable vkCmdSetDepthBiasEnable;
    PFN_vkCmdSetPrimitiveRestartEnable vkCmdSetPrimitiveRestartEnable;
    PFN_vkCmdSetTessellationDomainOriginEXT vkCmdSetTessellationDomainOrigin;
    PFN_vkCmdSetDepthClampEnableEXT vkCmdSetDepthClampEnable;
    PFN_vkCmdSetPolygonModeEXT vkCmdSetPolygonMode;
    PFN_vkCmdSetRasterizationSamplesEXT vkCmdSetRasterizationSamples;
    PFN_vkCmdSetSampleMaskEXT vkCmdSetSampleMask;
    PFN_vkCmdSetAlphaToCoverageEnableEXT vkCmdSetAlphaToCoverageEnable;
    PFN_vkCmdSetAlphaToOneEnableEXT vkCmdSetAlphaToOneEnable;
    PFN_vkCmdSetLogicOpEnableEXT vkCmdSetLogicOpEnable;
    PFN_vkCmdSetColorBlendEnableEXT vkCmdSetColorBlendEnable;
    PFN_vkCmdSetColorBlendEquationEXT vkCmdSetColorBlendEquation;
    PFN_vkCmdSetColorWriteMaskEXT vkCmdSetColorWriteMask;
    PFN_vkCmdSetRasterizationStreamEXT vkCmdSetRasterizationStream;
    PFN_vkCmdSetConservativeRasterizationModeEXT vkCmdSetConservativeRasterizationMode;
    PFN_vkCmdSetExtraPrimitiveOverestimationSizeEXT vkCmdSetExtraPrimitiveOverestimationSize;
    PFN_vkCmdSetDepthClipEnableEXT vkCmdSetDepthClipEnable;
    PFN_vkCmdSetSampleLocationsEnableEXT vkCmdSetSampleLocationsEnable;
    PFN_vkCmdSetColorBlendAdvancedEXT vkCmdSetColorBlendAdvanced;
    PFN_vkCmdSetProvokingVertexModeEXT vkCmdSetProvokingVertexMode;
    PFN_vkCmdSetLineRasterizationModeEXT vkCmdSetLineRasterizationMode;
    PFN_vkCmdSetLineStippleEnableEXT vkCmdSetLineStippleEnable;
    PFN_vkCmdSetDepthClipNegativeOneToOneEXT vkCmdSetDepthClipNegativeOneToOne;
    PFN_vkCmdCopyBuffer2 vkCmdCopyBuffer2;
    PFN_vkCmdCopyImage2 vkCmdCopyImage2;
    PFN_vkCmdBlitImage2 vkCmdBlitImage2;
    PFN_vkCmdCopyBufferToImage2 vkCmdCopyBufferToImage2;
    PFN_vkCmdCopyImageToBuffer2 vkCmdCopyImageToBuffer2;
    PFN_vkCmdResolveImage2 vkCmdResolveImage2;
    PFN_vkCmdSetColorWriteEnableEXT vkCmdSetColorWriteEnable;
    PFN_vkCmdSetEvent2KHR vkCmdSetEvent2;
    PFN_vkCmdResetEvent2KHR vkCmdResetEvent2;
    PFN_vkCmdWaitEvents2KHR vkCmdWaitEvents2;
    PFN_vkCmdPipelineBarrier2KHR vkCmdPipelineBarrier2;
    PFN_vkQueueSubmit2KHR vkQueueSubmit2;
    PFN_vkCmdWriteTimestamp2KHR vkCmdWriteTimestamp2;
    PFN_vkCmdBeginRenderingKHR vkCmdBeginRendering;
    PFN_vkCmdEndRenderingKHR vkCmdEndRendering;
    PFN_vkGetShaderModuleIdentifierEXT vkGetShaderModuleIdentifier;
    PFN_vkGetShaderModuleCreateInfoIdentifierEXT vkGetShaderModuleCreateInfoIdentifier;
} VulkanWrapper;

static inline void* findVulkanInstanceFunc(VulkanWrapper* vulkanWrapper, VkInstance instance, char* name) {
    char nameBuf[128];
    const char* suffixes[] = {"", "KHR", "EXT"};
    for (int i = 0; i < ARRAY_SIZE(suffixes); i++) {
        sprintf(nameBuf, "%s%s", name, suffixes[i]);
        PFN_vkVoidFunction voidFunc = vulkanWrapper->vkGetInstanceProcAddr(instance, nameBuf);
        if (voidFunc) return voidFunc;
    }
    return NULL;
}

static inline void* findVulkanDeviceFunc(VulkanWrapper* vulkanWrapper, VkDevice device, char* name) {
    char nameBuf[128];
    const char* suffixes[] = {"", "KHR", "EXT"};
    for (int i = 0; i < ARRAY_SIZE(suffixes); i++) {
        sprintf(nameBuf, "%s%s", name, suffixes[i]);
        PFN_vkVoidFunction voidFunc = vulkanWrapper->vkGetDeviceProcAddr(device, nameBuf);
        if (voidFunc) return voidFunc;
    }
    return NULL;
}

static inline void initVulkanWrapper(VulkanWrapper* vulkanWrapper, void* libvulkan) {
    memset(vulkanWrapper, 0, sizeof(VulkanWrapper));
    vulkanWrapper->vkCreateInstance = dlsym(libvulkan, "vkCreateInstance");
    vulkanWrapper->vkEnumerateInstanceVersion = dlsym(libvulkan, "vkEnumerateInstanceVersion");
    vulkanWrapper->vkEnumerateInstanceExtensionProperties = dlsym(libvulkan, "vkEnumerateInstanceExtensionProperties");
    vulkanWrapper->vkGetInstanceProcAddr = dlsym(libvulkan, "vkGetInstanceProcAddr");
    vulkanWrapper->vkGetDeviceProcAddr = dlsym(libvulkan, "vkGetDeviceProcAddr");
}

static inline void loadVulkanInstanceFuncs(VulkanWrapper* vulkanWrapper, VkInstance instance) {
#if ENABLE_VALIDATION_LAYER
    vulkanWrapper->vkCreateDebugReportCallback = findVulkanInstanceFunc(vulkanWrapper, instance, "vkCreateDebugReportCallback");
    vulkanWrapper->vkDestroyDebugReportCallback = findVulkanInstanceFunc(vulkanWrapper, instance, "vkDestroyDebugReportCallback");
#endif
    vulkanWrapper->vkDestroyInstance = findVulkanInstanceFunc(vulkanWrapper, instance, "vkDestroyInstance");
    vulkanWrapper->vkEnumeratePhysicalDevices = findVulkanInstanceFunc(vulkanWrapper, instance, "vkEnumeratePhysicalDevices");
    vulkanWrapper->vkGetPhysicalDeviceProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceProperties");
    vulkanWrapper->vkGetPhysicalDeviceQueueFamilyProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceQueueFamilyProperties");
    vulkanWrapper->vkGetPhysicalDeviceMemoryProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceMemoryProperties");
    vulkanWrapper->vkGetPhysicalDeviceFeatures = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceFeatures");
    vulkanWrapper->vkGetPhysicalDeviceFormatProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceFormatProperties");
    vulkanWrapper->vkGetPhysicalDeviceImageFormatProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceImageFormatProperties");
    vulkanWrapper->vkCreateDevice = findVulkanInstanceFunc(vulkanWrapper, instance, "vkCreateDevice");
    vulkanWrapper->vkEnumerateDeviceExtensionProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkEnumerateDeviceExtensionProperties");
    vulkanWrapper->vkGetPhysicalDeviceSparseImageFormatProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceSparseImageFormatProperties");
    vulkanWrapper->vkGetPhysicalDeviceSurfaceCapabilities = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceSurfaceCapabilities");
    vulkanWrapper->vkGetPhysicalDeviceSurfaceFormats = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceSurfaceFormats");
    vulkanWrapper->vkGetPhysicalDeviceSurfacePresentModes = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceSurfacePresentModes");
    vulkanWrapper->vkGetPhysicalDeviceFeatures2 = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceFeatures2");
    vulkanWrapper->vkGetPhysicalDeviceProperties2 = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceProperties2");
    vulkanWrapper->vkGetPhysicalDeviceFormatProperties2 = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceFormatProperties2");
    vulkanWrapper->vkGetPhysicalDeviceImageFormatProperties2 = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceImageFormatProperties2");
    vulkanWrapper->vkGetPhysicalDeviceQueueFamilyProperties2 = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceQueueFamilyProperties2");
    vulkanWrapper->vkGetPhysicalDeviceMemoryProperties2 = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceMemoryProperties2");
    vulkanWrapper->vkGetPhysicalDeviceSparseImageFormatProperties2 = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceSparseImageFormatProperties2");
    vulkanWrapper->vkGetPhysicalDeviceExternalBufferProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceExternalBufferProperties");
    vulkanWrapper->vkGetPhysicalDeviceExternalSemaphoreProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceExternalSemaphoreProperties");
    vulkanWrapper->vkGetPhysicalDeviceExternalFenceProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceExternalFenceProperties");
    vulkanWrapper->vkEnumeratePhysicalDeviceGroups = findVulkanInstanceFunc(vulkanWrapper, instance, "vkEnumeratePhysicalDeviceGroups");
    vulkanWrapper->vkGetPhysicalDevicePresentRectangles = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDevicePresentRectangles");
    vulkanWrapper->vkGetPhysicalDeviceMultisampleProperties = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceMultisampleProperties");
    vulkanWrapper->vkGetPhysicalDeviceCalibrateableTimeDomains = findVulkanInstanceFunc(vulkanWrapper, instance, "vkGetPhysicalDeviceCalibrateableTimeDomains");
}

static inline void loadVulkanDeviceFuncs(VulkanWrapper* vulkanWrapper, VkDevice device) {
    vulkanWrapper->vkDestroyDevice = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyDevice");
    vulkanWrapper->vkGetDeviceQueue = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceQueue");
    vulkanWrapper->vkQueueSubmit = findVulkanDeviceFunc(vulkanWrapper, device, "vkQueueSubmit");
    vulkanWrapper->vkQueueWaitIdle = findVulkanDeviceFunc(vulkanWrapper, device, "vkQueueWaitIdle");
    vulkanWrapper->vkDeviceWaitIdle = findVulkanDeviceFunc(vulkanWrapper, device, "vkDeviceWaitIdle");
    vulkanWrapper->vkAllocateMemory = findVulkanDeviceFunc(vulkanWrapper, device, "vkAllocateMemory");
    vulkanWrapper->vkFreeMemory = findVulkanDeviceFunc(vulkanWrapper, device, "vkFreeMemory");
    vulkanWrapper->vkMapMemory = findVulkanDeviceFunc(vulkanWrapper, device, "vkMapMemory");
    vulkanWrapper->vkUnmapMemory = findVulkanDeviceFunc(vulkanWrapper, device, "vkUnmapMemory");
    vulkanWrapper->vkFlushMappedMemoryRanges = findVulkanDeviceFunc(vulkanWrapper, device, "vkFlushMappedMemoryRanges");
    vulkanWrapper->vkInvalidateMappedMemoryRanges = findVulkanDeviceFunc(vulkanWrapper, device, "vkInvalidateMappedMemoryRanges");
    vulkanWrapper->vkGetDeviceMemoryCommitment = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceMemoryCommitment");
    vulkanWrapper->vkGetBufferMemoryRequirements = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetBufferMemoryRequirements");
    vulkanWrapper->vkBindBufferMemory = findVulkanDeviceFunc(vulkanWrapper, device, "vkBindBufferMemory");
    vulkanWrapper->vkGetImageMemoryRequirements = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetImageMemoryRequirements");
    vulkanWrapper->vkBindImageMemory = findVulkanDeviceFunc(vulkanWrapper, device, "vkBindImageMemory");
    vulkanWrapper->vkGetImageSparseMemoryRequirements = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetImageSparseMemoryRequirements");
    vulkanWrapper->vkQueueBindSparse = findVulkanDeviceFunc(vulkanWrapper, device, "vkQueueBindSparse");
    vulkanWrapper->vkCreateFence = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateFence");
    vulkanWrapper->vkDestroyFence = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyFence");
    vulkanWrapper->vkResetFences = findVulkanDeviceFunc(vulkanWrapper, device, "vkResetFences");
    vulkanWrapper->vkGetFenceStatus = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetFenceStatus");
    vulkanWrapper->vkWaitForFences = findVulkanDeviceFunc(vulkanWrapper, device, "vkWaitForFences");
    vulkanWrapper->vkCreateSemaphore = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateSemaphore");
    vulkanWrapper->vkDestroySemaphore = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroySemaphore");
    vulkanWrapper->vkCreateEvent = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateEvent");
    vulkanWrapper->vkDestroyEvent = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyEvent");
    vulkanWrapper->vkGetEventStatus = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetEventStatus");
    vulkanWrapper->vkSetEvent = findVulkanDeviceFunc(vulkanWrapper, device, "vkSetEvent");
    vulkanWrapper->vkResetEvent = findVulkanDeviceFunc(vulkanWrapper, device, "vkResetEvent");
    vulkanWrapper->vkCreateQueryPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateQueryPool");
    vulkanWrapper->vkDestroyQueryPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyQueryPool");
    vulkanWrapper->vkGetQueryPoolResults = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetQueryPoolResults");
    vulkanWrapper->vkResetQueryPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkResetQueryPool");
    vulkanWrapper->vkCreateBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateBuffer");
    vulkanWrapper->vkDestroyBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyBuffer");
    vulkanWrapper->vkCreateBufferView = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateBufferView");
    vulkanWrapper->vkDestroyBufferView = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyBufferView");
    vulkanWrapper->vkCreateImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateImage");
    vulkanWrapper->vkDestroyImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyImage");
    vulkanWrapper->vkGetImageSubresourceLayout = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetImageSubresourceLayout");
    vulkanWrapper->vkCreateImageView = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateImageView");
    vulkanWrapper->vkDestroyImageView = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyImageView");
    vulkanWrapper->vkCreateShaderModule = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateShaderModule");
    vulkanWrapper->vkDestroyShaderModule = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyShaderModule");
    vulkanWrapper->vkCreatePipelineCache = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreatePipelineCache");
    vulkanWrapper->vkDestroyPipelineCache = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyPipelineCache");
    vulkanWrapper->vkGetPipelineCacheData = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetPipelineCacheData");
    vulkanWrapper->vkMergePipelineCaches = findVulkanDeviceFunc(vulkanWrapper, device, "vkMergePipelineCaches");
    vulkanWrapper->vkCreateGraphicsPipelines = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateGraphicsPipelines");
    vulkanWrapper->vkCreateComputePipelines = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateComputePipelines");
    vulkanWrapper->vkDestroyPipeline = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyPipeline");
    vulkanWrapper->vkCreatePipelineLayout = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreatePipelineLayout");
    vulkanWrapper->vkDestroyPipelineLayout = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyPipelineLayout");
    vulkanWrapper->vkCreateSampler = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateSampler");
    vulkanWrapper->vkDestroySampler = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroySampler");
    vulkanWrapper->vkCreateDescriptorSetLayout = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateDescriptorSetLayout");
    vulkanWrapper->vkDestroyDescriptorSetLayout = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyDescriptorSetLayout");
    vulkanWrapper->vkCreateDescriptorPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateDescriptorPool");
    vulkanWrapper->vkDestroyDescriptorPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyDescriptorPool");
    vulkanWrapper->vkResetDescriptorPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkResetDescriptorPool");
    vulkanWrapper->vkAllocateDescriptorSets = findVulkanDeviceFunc(vulkanWrapper, device, "vkAllocateDescriptorSets");
    vulkanWrapper->vkFreeDescriptorSets = findVulkanDeviceFunc(vulkanWrapper, device, "vkFreeDescriptorSets");
    vulkanWrapper->vkUpdateDescriptorSets = findVulkanDeviceFunc(vulkanWrapper, device, "vkUpdateDescriptorSets");
    vulkanWrapper->vkCreateFramebuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateFramebuffer");
    vulkanWrapper->vkDestroyFramebuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyFramebuffer");
    vulkanWrapper->vkCreateRenderPass = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateRenderPass");
    vulkanWrapper->vkDestroyRenderPass = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyRenderPass");
    vulkanWrapper->vkGetRenderAreaGranularity = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetRenderAreaGranularity");
    vulkanWrapper->vkCreateCommandPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateCommandPool");
    vulkanWrapper->vkDestroyCommandPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyCommandPool");
    vulkanWrapper->vkResetCommandPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkResetCommandPool");
    vulkanWrapper->vkAllocateCommandBuffers = findVulkanDeviceFunc(vulkanWrapper, device, "vkAllocateCommandBuffers");
    vulkanWrapper->vkFreeCommandBuffers = findVulkanDeviceFunc(vulkanWrapper, device, "vkFreeCommandBuffers");
    vulkanWrapper->vkBeginCommandBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkBeginCommandBuffer");
    vulkanWrapper->vkEndCommandBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkEndCommandBuffer");
    vulkanWrapper->vkResetCommandBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkResetCommandBuffer");
    vulkanWrapper->vkCmdBindPipeline = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBindPipeline");
    vulkanWrapper->vkCmdSetViewport = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetViewport");
    vulkanWrapper->vkCmdSetScissor = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetScissor");
    vulkanWrapper->vkCmdSetLineWidth = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetLineWidth");
    vulkanWrapper->vkCmdSetDepthBias = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthBias");
    vulkanWrapper->vkCmdSetBlendConstants = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetBlendConstants");
    vulkanWrapper->vkCmdSetDepthBounds = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthBounds");
    vulkanWrapper->vkCmdSetStencilCompareMask = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetStencilCompareMask");
    vulkanWrapper->vkCmdSetStencilWriteMask = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetStencilWriteMask");
    vulkanWrapper->vkCmdSetStencilReference = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetStencilReference");
    vulkanWrapper->vkCmdBindDescriptorSets = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBindDescriptorSets");
    vulkanWrapper->vkCmdBindIndexBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBindIndexBuffer");
    vulkanWrapper->vkCmdBindVertexBuffers = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBindVertexBuffers");
    vulkanWrapper->vkCmdDraw = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDraw");
    vulkanWrapper->vkCmdDrawIndexed = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDrawIndexed");
    vulkanWrapper->vkCmdDrawIndirect = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDrawIndirect");
    vulkanWrapper->vkCmdDrawIndexedIndirect = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDrawIndexedIndirect");
    vulkanWrapper->vkCmdDispatch = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDispatch");
    vulkanWrapper->vkCmdDispatchIndirect = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDispatchIndirect");
    vulkanWrapper->vkCmdCopyBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyBuffer");
    vulkanWrapper->vkCmdCopyImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyImage");
    vulkanWrapper->vkCmdBlitImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBlitImage");
    vulkanWrapper->vkCmdCopyBufferToImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyBufferToImage");
    vulkanWrapper->vkCmdCopyImageToBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyImageToBuffer");
    vulkanWrapper->vkCmdUpdateBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdUpdateBuffer");
    vulkanWrapper->vkCmdFillBuffer = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdFillBuffer");
    vulkanWrapper->vkCmdClearColorImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdClearColorImage");
    vulkanWrapper->vkCmdClearDepthStencilImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdClearDepthStencilImage");
    vulkanWrapper->vkCmdClearAttachments = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdClearAttachments");
    vulkanWrapper->vkCmdResolveImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdResolveImage");
    vulkanWrapper->vkCmdSetEvent = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetEvent");
    vulkanWrapper->vkCmdResetEvent = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdResetEvent");
    vulkanWrapper->vkCmdWaitEvents = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdWaitEvents");
    vulkanWrapper->vkCmdPipelineBarrier = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdPipelineBarrier");
    vulkanWrapper->vkCmdBeginQuery = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBeginQuery");
    vulkanWrapper->vkCmdEndQuery = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdEndQuery");
    vulkanWrapper->vkCmdBeginConditionalRendering = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBeginConditionalRendering");
    vulkanWrapper->vkCmdEndConditionalRendering = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdEndConditionalRendering");
    vulkanWrapper->vkCmdResetQueryPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdResetQueryPool");
    vulkanWrapper->vkCmdWriteTimestamp = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdWriteTimestamp");
    vulkanWrapper->vkCmdCopyQueryPoolResults = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyQueryPoolResults");
    vulkanWrapper->vkCmdPushConstants = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdPushConstants");
    vulkanWrapper->vkCmdBeginRenderPass = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBeginRenderPass");
    vulkanWrapper->vkCmdNextSubpass = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdNextSubpass");
    vulkanWrapper->vkCmdEndRenderPass = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdEndRenderPass");
    vulkanWrapper->vkCmdExecuteCommands = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdExecuteCommands");
    vulkanWrapper->vkCreateSwapchain = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateSwapchain");
    vulkanWrapper->vkDestroySwapchain = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroySwapchain");
    vulkanWrapper->vkGetSwapchainImages = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetSwapchainImages");
    vulkanWrapper->vkAcquireNextImage = findVulkanDeviceFunc(vulkanWrapper, device, "vkAcquireNextImage");
    vulkanWrapper->vkQueuePresent = findVulkanDeviceFunc(vulkanWrapper, device, "vkQueuePresent");
    vulkanWrapper->vkCmdPushDescriptorSet = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdPushDescriptorSet");
    vulkanWrapper->vkTrimCommandPool = findVulkanDeviceFunc(vulkanWrapper, device, "vkTrimCommandPool");
    vulkanWrapper->vkGetMemoryFd = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetMemoryFd");
    vulkanWrapper->vkGetSemaphoreFd = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetSemaphoreFd");
    vulkanWrapper->vkGetFenceFd = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetFenceFd");
    vulkanWrapper->vkGetDeviceGroupPeerMemoryFeatures = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceGroupPeerMemoryFeatures");
    vulkanWrapper->vkBindBufferMemory2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkBindBufferMemory2");
    vulkanWrapper->vkBindImageMemory2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkBindImageMemory2");
    vulkanWrapper->vkCmdSetDeviceMask = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDeviceMask");
    vulkanWrapper->vkAcquireNextImage2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkAcquireNextImage2");
    vulkanWrapper->vkCmdDispatchBase = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDispatchBase");
    vulkanWrapper->vkCreateDescriptorUpdateTemplate = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateDescriptorUpdateTemplate");
    vulkanWrapper->vkDestroyDescriptorUpdateTemplate = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroyDescriptorUpdateTemplate");
    vulkanWrapper->vkUpdateDescriptorSetWithTemplate = findVulkanDeviceFunc(vulkanWrapper, device, "vkUpdateDescriptorSetWithTemplate");
    vulkanWrapper->vkCmdSetSampleLocations = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetSampleLocations");
    vulkanWrapper->vkGetBufferMemoryRequirements2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetBufferMemoryRequirements2");
    vulkanWrapper->vkGetImageMemoryRequirements2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetImageMemoryRequirements2");
    vulkanWrapper->vkGetImageSparseMemoryRequirements2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetImageSparseMemoryRequirements2");
    vulkanWrapper->vkGetDeviceBufferMemoryRequirements = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceBufferMemoryRequirements");
    vulkanWrapper->vkGetDeviceImageMemoryRequirements = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceImageMemoryRequirements");
    vulkanWrapper->vkGetDeviceImageSparseMemoryRequirements = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceImageSparseMemoryRequirements");
    vulkanWrapper->vkCreateSamplerYcbcrConversion = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateSamplerYcbcrConversion");
    vulkanWrapper->vkDestroySamplerYcbcrConversion = findVulkanDeviceFunc(vulkanWrapper, device, "vkDestroySamplerYcbcrConversion");
    vulkanWrapper->vkGetDeviceQueue2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceQueue2");
    vulkanWrapper->vkGetDescriptorSetLayoutSupport = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDescriptorSetLayoutSupport");
    vulkanWrapper->vkGetCalibratedTimestamps = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetCalibratedTimestamps");
    vulkanWrapper->vkCreateRenderPass2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCreateRenderPass2");
    vulkanWrapper->vkCmdBeginRenderPass2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBeginRenderPass2");
    vulkanWrapper->vkCmdNextSubpass2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdNextSubpass2");
    vulkanWrapper->vkCmdEndRenderPass2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdEndRenderPass2");
    vulkanWrapper->vkGetSemaphoreCounterValue = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetSemaphoreCounterValue");
    vulkanWrapper->vkWaitSemaphores = findVulkanDeviceFunc(vulkanWrapper, device, "vkWaitSemaphores");
    vulkanWrapper->vkSignalSemaphore = findVulkanDeviceFunc(vulkanWrapper, device, "vkSignalSemaphore");
    vulkanWrapper->vkGetAndroidHardwareBufferPropertiesANDROID = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetAndroidHardwareBufferPropertiesANDROID");
    vulkanWrapper->vkCmdDrawIndirectCount = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDrawIndirectCount");
    vulkanWrapper->vkCmdDrawIndexedIndirectCount = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDrawIndexedIndirectCount");
    vulkanWrapper->vkCmdBindTransformFeedbackBuffers = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBindTransformFeedbackBuffers");
    vulkanWrapper->vkCmdBeginTransformFeedback = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBeginTransformFeedback");
    vulkanWrapper->vkCmdEndTransformFeedback = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdEndTransformFeedback");
    vulkanWrapper->vkCmdBeginQueryIndexed = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBeginQueryIndexed");
    vulkanWrapper->vkCmdEndQueryIndexed = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdEndQueryIndexed");
    vulkanWrapper->vkCmdDrawIndirectByteCount = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdDrawIndirectByteCount");
    vulkanWrapper->vkGetBufferOpaqueCaptureAddress = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetBufferOpaqueCaptureAddress");
    vulkanWrapper->vkGetBufferDeviceAddress = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetBufferDeviceAddress");
    vulkanWrapper->vkGetDeviceMemoryOpaqueCaptureAddress = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetDeviceMemoryOpaqueCaptureAddress");
    vulkanWrapper->vkCmdSetLineStipple = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetLineStipple");
    vulkanWrapper->vkCmdSetCullMode = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetCullMode");
    vulkanWrapper->vkCmdSetFrontFace = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetFrontFace");
    vulkanWrapper->vkCmdSetPrimitiveTopology = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetPrimitiveTopology");
    vulkanWrapper->vkCmdSetViewportWithCount = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetViewportWithCount");
    vulkanWrapper->vkCmdSetScissorWithCount = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetScissorWithCount");
    vulkanWrapper->vkCmdBindVertexBuffers2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBindVertexBuffers2");
    vulkanWrapper->vkCmdSetDepthTestEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthTestEnable");
    vulkanWrapper->vkCmdSetDepthWriteEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthWriteEnable");
    vulkanWrapper->vkCmdSetDepthCompareOp = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthCompareOp");
    vulkanWrapper->vkCmdSetDepthBoundsTestEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthBoundsTestEnable");
    vulkanWrapper->vkCmdSetStencilTestEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetStencilTestEnable");
    vulkanWrapper->vkCmdSetStencilOp = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetStencilOp");
    vulkanWrapper->vkCmdSetRasterizerDiscardEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetRasterizerDiscardEnable");
    vulkanWrapper->vkCmdSetDepthBiasEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthBiasEnable");
    vulkanWrapper->vkCmdSetPrimitiveRestartEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetPrimitiveRestartEnable");
    vulkanWrapper->vkCmdSetTessellationDomainOrigin = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetTessellationDomainOrigin");
    vulkanWrapper->vkCmdSetDepthClampEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthClampEnable");
    vulkanWrapper->vkCmdSetPolygonMode = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetPolygonMode");
    vulkanWrapper->vkCmdSetRasterizationSamples = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetRasterizationSamples");
    vulkanWrapper->vkCmdSetSampleMask = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetSampleMask");
    vulkanWrapper->vkCmdSetAlphaToCoverageEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetAlphaToCoverageEnable");
    vulkanWrapper->vkCmdSetAlphaToOneEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetAlphaToOneEnable");
    vulkanWrapper->vkCmdSetLogicOpEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetLogicOpEnable");
    vulkanWrapper->vkCmdSetColorBlendEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetColorBlendEnable");
    vulkanWrapper->vkCmdSetColorBlendEquation = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetColorBlendEquation");
    vulkanWrapper->vkCmdSetColorWriteMask = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetColorWriteMask");
    vulkanWrapper->vkCmdSetRasterizationStream = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetRasterizationStream");
    vulkanWrapper->vkCmdSetConservativeRasterizationMode = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetConservativeRasterizationMode");
    vulkanWrapper->vkCmdSetExtraPrimitiveOverestimationSize = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetExtraPrimitiveOverestimationSize");
    vulkanWrapper->vkCmdSetDepthClipEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthClipEnable");
    vulkanWrapper->vkCmdSetSampleLocationsEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetSampleLocationsEnable");
    vulkanWrapper->vkCmdSetColorBlendAdvanced = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetColorBlendAdvanced");
    vulkanWrapper->vkCmdSetProvokingVertexMode = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetProvokingVertexMode");
    vulkanWrapper->vkCmdSetLineRasterizationMode = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetLineRasterizationMode");
    vulkanWrapper->vkCmdSetLineStippleEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetLineStippleEnable");
    vulkanWrapper->vkCmdSetDepthClipNegativeOneToOne = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetDepthClipNegativeOneToOne");
    vulkanWrapper->vkCmdCopyBuffer2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyBuffer2");
    vulkanWrapper->vkCmdCopyImage2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyImage2");
    vulkanWrapper->vkCmdBlitImage2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBlitImage2");
    vulkanWrapper->vkCmdCopyBufferToImage2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyBufferToImage2");
    vulkanWrapper->vkCmdCopyImageToBuffer2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdCopyImageToBuffer2");
    vulkanWrapper->vkCmdResolveImage2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdResolveImage2");
    vulkanWrapper->vkCmdSetColorWriteEnable = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetColorWriteEnable");
    vulkanWrapper->vkCmdSetEvent2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdSetEvent2");
    vulkanWrapper->vkCmdResetEvent2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdResetEvent2");
    vulkanWrapper->vkCmdWaitEvents2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdWaitEvents2");
    vulkanWrapper->vkCmdPipelineBarrier2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdPipelineBarrier2");
    vulkanWrapper->vkQueueSubmit2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkQueueSubmit2");
    vulkanWrapper->vkCmdWriteTimestamp2 = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdWriteTimestamp2");
    vulkanWrapper->vkCmdBeginRendering = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdBeginRendering");
    vulkanWrapper->vkCmdEndRendering = findVulkanDeviceFunc(vulkanWrapper, device, "vkCmdEndRendering");
    vulkanWrapper->vkGetShaderModuleIdentifier = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetShaderModuleIdentifier");
    vulkanWrapper->vkGetShaderModuleCreateInfoIdentifier = findVulkanDeviceFunc(vulkanWrapper, device, "vkGetShaderModuleCreateInfoIdentifier");
}

#endif